VirtualEngine/Lability

- Src/LabHostDefaults.ps1
Assuming that #22 is a bug, I have created the following fix.
Instead of testing that the path exist, I test that the specified drive exist, and that the specified path is valid.
Let me know what you think.
> Fix #22 (assuming it is a bug)

- Lib/BootStrap.ps1
- Lib/ConfigurationData.ps1
- Lib/DiskImage.ps1
- Lib/DscModule.ps1
- Lib/DscResource.ps1
- Lib/DscResourceModule.ps1
- Lib/Internal.ps1
- Lib/Resource.ps1
- Lib/UnattendXml.ps1
- Lib/ZipArchive.ps1
- Resources.psd1
- Src/Lab.ps1
- Src/LabConfiguration.ps1
- Src/LabHostConfiguration.ps1
- Src/LabImage.ps1
- Src/LabResource.ps1
- Src/LabVM.ps1
- Src/LabVMSnapshot.ps1
- VirtualEngineLab.psm1
- en-US/Example.ps1
Fix a bunch of PSScriptAnalyzer warnings as part of code review #30
> Fix a bunch of PSScriptAnalyzer warnings

- Src/LabConfiguration.ps1
- Src/LabHostConfiguration.ps1
- Src/LabHostDefaults.ps1
- Src/LabMedia.ps1
- Src/LabVMDefaults.ps1
- Tests/Src/LabHostDefaults.Tests.ps1
- Tests/Src/LabResource.Tests.ps1
- Tests/Src/LabVM.Tests.ps1
- Tests/Src/LabVMDefaults.Tests.ps1
Fix PSUseSingularNouns warnings and add aliases for old PluralNouns as part of Code Review #30
> Fix PSUseSingularNouns warnings and add aliases for old PluralNouns

- Readme.md
- Src/LabConfiguration.ps1
- Src/LabHostConfiguration.ps1
- Src/LabVM.ps1
- Src/LabVMDisk.ps1
* Adds Write-Progress support to Reset-LabVM, New-LabVM, Remove-LabVM and Test-LabConfiguration
* Adds -IgnorePendingReboot parameter to Start-LabConfiguration
* Removes extraneous verbose output from Get-CimInstance in Test-LabHostConfiguration
* Fixes bug in Test-LabVM where VM's prefixed name was not resolved causing calls to TestLabVMDisk and TestLabVirtualMachine to fail
> Adds Additional Write-Progress

- Lib/ConfigurationData.ps1
- Readme.md
- Resources.psd1
- Src/Lab.ps1
- Src/LabConfiguration.ps1
- Src/LabMedia.ps1
- Src/LabResource.ps1
- Src/LabSwitch.ps1
- Src/LabVM.ps1
- Tests/Lib/ConfigurationData.Tests.ps1
- Tests/Src/LabConfiguration.Tests.ps1
- Tests/Src/LabMedia.Tests.ps1
- Tests/Src/LabResource.Tests.ps1
* Fixes #89
* Adds optional -ConfigurationData switch to Remove-LabVM to support prefixed configurations.
* Deprecates ConvertToConfigurationData function in favour of the native [ArgumentToConfigurationDataTransformationAttribute()].
> Fixes bug in Get-LabVM where VMs' prefixed name was not resolved correctly

- Lib/Module.ps1
- Readme.md
- Src/LabVMDiskFile.ps1
Fixes hard-coded '\Program Files\' directory when enumerating modules to resolve host localisation issues
> Fixes hard-coded '\Program Files\' directory when enumerating modules

- Lability.psd1
- Readme.md
* Fixes bug in custom media enumeration in Start-LabConfiguration (#97).
* Removes importing module warnings when enumerating local module availability.
* Fixes bug when invoking lab deployments with PSake (#104).
* Adds Server 2016 Technical Preview 5 media.
* Fixes bug in Import-LabHostConfiguration where VM defaults contains reference to custom media.
* Fixes long local module enumeration times on build 14295 and later.
* Fixes hard-coded '\Program Files\' directory when enumerating modules to resolve localisation issues.
* Tests computer name for validity before creating a virtual machine (#109).
> Releasing 0.9.11

- Src/LabVM.ps1
Hey,
I've been having an issue when defining multiple virtual switches in my config file as the switches aren't iterated through, and therefore Test-LabVM is trying to validate against the actual array.
The error I was getting was:
```powershell
Testing Virtual Switch configuration 'System.Object[]'.
Test-LabVM : Cannot process argument transformation on parameter 'Name'. Cannot convert 
value to type System.String.
At C:\Program Files\WindowsPowerShell\Modules\Lability\Src\LabConfiguration.ps1:40 char:32
+ ... onfigured = Test-LabVM -Name $node.NodeName -ConfigurationData $Confi ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [Test-LabVM], ParameterBindingArgumentTran 
sformationException
+ FullyQualifiedErrorId : …
```
> Iterate through all switches when running Test-LabVM

- Lability.psd1
- Readme.md
* Updates Windows 10 media to build 14393 (1607).
* Adds `WIN10_x64_Enterprise_LTSB_EN_Eval` and `WIN10_x86_Enterprise_LTSB_EN_Eval` media.
* Adds July 2016 CU hotfix (KB3163912) to Windows 10 x86 and x64 LTSB media.
* Adds June 2016 CU hotfix (KB3172982) to WS2016 TP5 default lab media registrations.
* Replaces Get-LabVMDefaults, Set-LabVMDefaults aliases with proxy functions with deprecation warning.
* Replaces Get-LabHostDefaults, Set-LabHostDefaults aliases with proxy functions with deprecation warning.
* Adds support for injecting modules in VMs (#106).
* Adds `NonNodeData\Lability\Module = @()` and `Node\Lability_Module` support.
* Adds `Provider = 'FileSystem'` support to DSC resource and PowerShell module definitions.
* Deprecates LabNode functionality (will move to the …
> Releasing v0.10.0

- Examples/TestLabGuide.ps1
- Lability.Format.ps1xml
- Lability.psd1
- Lib/BootStrap.ps1
- Lib/DiskImage.ps1
- Readme.md
- Resources.psd1
- Src/LabImage.ps1
- Src/LabMedia.ps1
- Src/LabResource.ps1
- Src/LabVMDiskFile.ps1
* Removes local Administrator password from verbose output (#140)
* Reinstates the xDhcpServerOption 'Router' parameter in example TestLabGuide.ps1
* Fixes bug in 'IsLocal' resource when combined with a custom 'DestinationPath' location
* Adds output formatting to lab images and media
> Adds output formatting

- Lability.psd1
- Readme.md
* Updates bundled xHyper-V DSC resource module to 3.5.0.0
* Updates bundled xPendingReboot DSC resource module to 0.3.0.0
* Fixes calls to stop/start Shell Hardware Detection service on Server Core (#175)
* Fixes incorrect WIN10_x86_Enterprise_EN_Eval uri (#183)
* Fixes .VHD files not being removed (#182)
* Fixes .VHDX files not being dismounted when there are errors creating the disk (#185)
* Adds Windows Management Framework 5.1 evaluation media
* Updates examples with xNetworking v3.0.0.0 breaking change (#172)
> Releasing 0.10.2

- Lability.psd1
- Readme.md
* Adds -Confirm/-WhatIf support to:
* Start-LabConfiguration, Remove-LabConfiguration
* Start-Lab, Stop-Lab, Reset-Lab and Restore-Lab
* Searches $PWD folder and EnvironmentName sub folder for .mof files (#181)
* Throws error if unsupported module values are defined (#170)
* Fixes error copying resource files into custom VHD Windows media (#193)
* Adds credential encryption/certificate support on Nano server
* Permits overriding VM generation with the Media\CustomData\VmGeneration property (#194)
* Adds -RepositoryUri parameter to Set-LabHostDefault to support internal repositories (partially implements #195)
* Changes default PowerShell gallery URI to HTTPS
* Removes mounted ISOs when parent VHD/X image creation fails (#166)
* Updates bundled xHyper-V DSC resource module to 3.7.0.0
* …
> Releasing version 0.10.3

- Src/Private/Assert-TimeZone.ps1
Fix an issue where the timezone would not be applied on a non-English (German) host OS because the string "Mitteleuropäische Zeit" would be written to the injected unattend.xml instead of the correct string "W. Europe Standard Time".
On a non-English OS, the ID contains the English timezone string, while the StandardName contains a localized version; see the following output for [TimeZoneInfo]::FindSystemTimeZoneById:
For the timezone to be applied correctly via unattend.xml, the English string should be used.
> use timezone Id instead of localized StandardName

- Lability.psd1
- Readme.md
* Removes "experimental" tag from attaching multiple VHD files to VMs (#218)
* Adds support for creating both fixed and dynamic VHD files (#99)
* Adds support for creating empty/blank media (#135)
* Removes errant "Specify MaximumSizeBytes property" xVHD errors
* Adds support for configuring the WSMan MaxEnvelopeSizeKb setting (#282)
* Updates built-in Windows 10 Enterprise evaluation media with the 1803 'April 2018 Update' ISOs
* Fixes removal of additional disks/VHDs when using an environment prefix (#292)
* Fixes bug in automatic checkpoint detection on Windows 10 build 1703 (and earlier) (#294)
* Changes the default internal virtual switch name from 'Internal vSwitch' to 'Default Switch'
> Releasing 0.15.0

- Src/Public/New-LabImage.ps1
- Tests/Unit/Src/Public/New-LabImage.Tests.ps1
VHD media files weren't being downloaded following changes in 0.15.0, this adds the download back in. Also added a test for this.
> Add Invoke-LabMediaImageDownload to VHD creation - fixes #309

- Readme.md
This is to correct the link in README.md to the article "Using Lability, DSC and ARM to define and deploy multi-VM environments." This will close issue #322 
Original link is [https://blogs.blackmarble.co.uk/blogs/rhepworth/post/2017/03/02/Define-Once-Deploy-Everywhere-(Sort-of…)](https://blogs.blackmarble.co.uk/blogs/rhepworth/post/2017/03/02/Define-Once-Deploy-Everywhere-(Sort-of…)).
Corrected link is [https://blogs.blackmarble.co.uk/rhepworth/2017/03/02/define-once-deploy-everywhere-sort-of/](https://blogs.blackmarble.co.uk/rhepworth/2017/03/02/define-once-deploy-everywhere-sort-of/)
> Correct link for 'Using Lability, DSC and ARM' site

- Tests/Unit/Src/Public/Register-LabMedia.Tests.ps1
Suggested fix for #336 by mocking Invoke-RestMethod, instead of writing file to "TestDrive:".
> Mocking of Invoke-RestMethod instead of writing to TestDrive (fix #336)

- ChangeLog.md
- Config/VMDefaults.json
- Src/Private/Get-ConfigurationData.ps1
- Src/Private/New-LabVirtualMachine.ps1
- Src/Private/Resolve-NodePropertyValue.ps1
- Src/Private/Set-LabVMDiskFileUnattendXml.ps1
- Src/Public/Set-LabVMDefault.ps1
- Tests/Unit/Src/Private/Get-ConfigurationData.Tests.ps1
- Tests/Unit/Src/Private/Resolve-NodePropertyValue.Tests.ps1
- Tests/Unit/Src/Private/Set-LabVMDiskFileUnattendXml.Tests.ps1
- Tests/Unit/Src/Public/Set-LabVMDefault.Tests.ps1
* Fixes #335`
* Adds `-UseNetBIOSName` parameter to `Set-LabVMDefault` to enforce VM and disk filenames are created using NetBIOS name format
> Adds support for defining node names with FQDNs

- en-US/about_Bootstrap.help.txt
Not sure if this was intentional or not, but the example for Media custom bootstrap has a comment on enabling the admin account and the actual code is missing. Added the code.
Feel free to reject the PR if I misunderstood.
> Added code row to enable admin account

- Readme.md
Hello.
I wrote a tutorial for Lability, and thought you might like to include a link to it in your docs. I found Lability super useful at my job last year, and wanted to give back and also help others get started. I actually intended to open a PR like this 6 months ago but got busy with other projects, so it kinda sat there for a while. It starts very simple and builds to a more complex lab. It's complete-ish at this point, although it could probably use an editor.
If you're not interested that's cool. Alternatively, feel free to copy anything you like from what I've written and include it in Lability. You can see the source at https://github.com/mrled/lability-tutorial
Thanks for such a cool project! <3
> Add link to Lability tutorial

- ChangeLog.md
- Config/LegacyMedia/WIN10_x64_Enterprise_2004_EN_Eval.json
- Config/LegacyMedia/WIN10_x86_Enterprise_2004_EN_Eval.json
- Config/Media.json
- Lability.psd1
- Src/Private/New-LabBootStrap.ps1
- Src/Private/Set-LabBootStrap.ps1
* Updates default Windows 10 evaluation media to Windows 10 20H2 (2009)
* Adds Windows 10 20H1 (2004) evaluation media
* Adds aliases for latest Windows 10 evaluation media avoiding breaking existing VHD/X chains (or in future)
* Fixes bug in custom bootstrap injection with Regex substitution string(s), e.g. $&
> Releasing v0.20.0

- Config/Media.json
Hi,
I was following one of the lability tutorials listed in the repository readme and had a problem using the code listed. I think there is a problem in media.json where one of the resources has a "Url" field that actually should be "Uri". This pull request fixes this.
To recreate the issue do:
`Invoke-LabResourceDownload -MediaID 'WIN10_x64_Enterprise_21H2_EN_Eval'`
Without the fix it outputs: 
New-Object : A constructor was not found. Cannot find an appropriate constructor for type System.Uri.
At line:36 char:21
\+ ... $mediaUri = New-Object -TypeName System.Uri -ArgumentList $Media.Uri; ...
etc...
Changing the field from "Url" to "Uri" fixes this.
> Rename field 'Url' to 'Uri' in media.json

- ChangeLog.md
- Lability.psd1
Updates `ChangeLog.md` and bumps version to `0.21.1` for release
> Fixes bug in `WIN10_x64_Enterprise_21H2_EN_Eval` media link

- ChangeLog.md
- Config/LegacyMedia/WIN11_x64_Enterprise_21H2_EN_Eval.json
- Config/Media.json
- Config/VMDefaults.json
- Lability.psd1
Adds Adds Windows Server 2022 evaluation media
Updates default VM media to '2022_x64_Datacenter_EN_Eval' (#406)
> Adds Windows 11 Enterprise 22H2 (2209) evaluation media

- ChangeLog.md
- Config/LegacyMedia/WIN11_x64_Enterprise_21H2_EN_Eval.json
- Config/Media.json
- Config/VMDefaults.json
- Lability.psd1
* Adds Windows 11 Enterprise 22H2 (2209) evaluation media
* Adds Adds Windows Server 2022 evaluation media
* Updates default VM media from `2019_x64_Standard_EN_Eval` to `2022_x64_Datacenter_EN_Eval` (#406)
> Releasing v0.22.0

- ChangeLog.md
- Lability.psd1
* Fixes PSScriptAnalyzer 1.21.0 test failures
* Fixes Windows 11 Enterprise 22H2 (2209) evaluation media download link
* Adds Windows 10 Enterprise 22H2 (2209) evaluation media
* Updates default Windows 10 evaluation media to Windows 10 22H2 (2209)
> Releasing 0.23.0

- Config/Media.json
I use both of these ISO's so adding them for use
Closed the last PR as don't know what happened with it and appvayor not working
partially fixes #433 - Seems there's no ISO for EN_GB ARM Win 11 version as it's pointing to en-us or was whilst looking at it
> Add's Server 2025 EN & W11 24H2 iso's for EN and EN_GB to Media.json

- Build.PSake.ps1
- ChangeLog.md
* Adds Windows 11 Enterprise 24H2 (2410) evaluation media
* Adds EN-US ARM64 media (WIN11_ARM64_Enterprise_24H2_EN_Eval)
* Adds EN-GB x64 media (WIN11_x64_Enterprise_24H2_ENGB_Eval)
* Moves all Windows Server 2012 R2 media to legacy media due to end of support
* Assigns mounted VHD(X) a drive letter - if not automatically assigned
* Updates build pipeline with DotNet Core Azure Sign Tool (and removes VE_Certificate_2023.pfx)
> Releasing 0.26.0
