VirtualEngine/Lability

Config/Media.json

Don't know if you are interested in supporting tech previews in the module. But if you are, this adds the Windows Server 2016 Technical Preview images to the media config

Add Windows Server 2016 Technical Preview 4 images

---

Config/Media.json
Lib/BootStrap.ps1
Lib/ConfigurationData.ps1
Lib/DiskImage.ps1
Lib/DscModule.ps1
Lib/Resource.ps1
Lib/UnattendXml.ps1
Lib/WindowsImage.ps1
Resources.psd1
Src/LabHostConfiguration.ps1
Src/LabHostDefaults.ps1
Src/LabImage.ps1
Src/LabMedia.ps1
Src/LabVM.ps1
Src/LabVMDefaults.ps1
Src/LabVMDiskFile.ps1
Tests/Lib/BootStrap.Tests.ps1
Tests/Lib/DiskImage.Tests.ps1
Tests/Lib/WindowsImage.Tests.ps1
Tests/Src/LabImage.Tests.ps1
Tests/Src/LabVM.Tests.ps1
Tests/Src/LabVMDiskFile.Tests.ps1
VirtualEngineLab.psd1
en-US/Example.psd1
en-US/NanoExample.ps1
en-US/NanoExample.psd1

* Fixes #32
* Adds initial support for Nano server in 2016 TP4
* Adds Nano server media
* Implements Media.CustomData.WimPath functionality
* Implements Media.CustomData.PackagePath functionality
* Implements Media.CustomData.Package functionality
* Implements Media.CustomData.SetupComplete functionality
* Adds example NanoExample.ps1 and .psd1 files

WIM ISO Support

---

Resources.psd1
Src/LabHostDefaults.ps1
Src/LabMedia.ps1
Src/LabSwitch.ps1
Src/LabVM.ps1
Tests/Src/LabSwitch.Tests.ps1
Tests/Src/LabVM.Tests.ps1
en-US/NanoExample.psd1
en-US/about_Labililty.help.txt
en-US/about_Networking.help.txt

* Adds support for utilising existing virtual switches without specifying a type
* Allows use of existing NAT virtual switches!
* Fixes 47

Adds existing switch support

---

Lability.psd1
Src/LabImage.ps1
Tests/Src/LabImage.Tests.ps1

* Fixes bug in Get-LabImage enumeration with custom VHD media
* Fixes bug where environment variables are not expanded in Get-LabImage

Fixes bugs in Get-LabImage

---

Lability.psd1
Lability.psm1
Lib/BootStrap.ps1
Lib/ConfigurationData.ps1
Lib/DiskImage.ps1
Lib/DscModule.ps1
Lib/DscResource.ps1
Lib/DscResourceModule.ps1
Lib/Internal.ps1
Lib/Module.ps1
Lib/VirtualMachine.ps1
Lib/WindowsImage.ps1
Lib/ZipArchive.ps1
Src/LabHostConfiguration.ps1
Src/LabMedia.ps1
Src/LabResource.ps1
Tests/Src/LabResource.Tests.ps1
en-US/about_CustomResources.help.txt

* Adds support for DestinationPath property in custom resources
* Explicitly exports functions to enable module auto-loading with dot-sourced ps1 files
* Fixes array coercion bug where additional custom media cannot be added
* Formatting updates

Adds support for DestinationPath property in custom resources

---

Lability.psd1
Lib/BootStrap.ps1
Lib/VirtualMachine.ps1
Resources.psd1
Src/LabImage.ps1
Src/LabVMDiskFile.ps1
Tests/Lib/VirtualMachine.Tests.ps1
Tests/Src/LabMedia.Tests.ps1

* Updates bootstrap to remove existing configuration document(s) and restart WMI
* Fixes bug in VM generation when custom partition style is defined
* Fixes bug when creating lab image from custom VHD media
* Removes existing DSC resources on nodes' VHD(X)s if present when using custom images

Fixes bootstrap on v4 implementations

---

Lib/BootStrap.ps1
Lib/ConfigurationData.ps1

Also fixes error setting custom bootstrap in custom media due to JSON conversion depth :@

Fixes error in bootstrap transcript path stopping bootstrap executing

---

Lib/DscResource.ps1

Fixes the issue with Get-LabHostConfiguration function.

Fix #62 PR

---

DSCResources/xHyper-V/DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1
DSCResources/xHyper-V/DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.schema.mof
DSCResources/xHyper-V/DSCResources/MSFT_xVMSwitch/MSFT_xVMSwitch.psm1
DSCResources/xHyper-V/DSCResources/MSFT_xVMSwitch/MSFT_xVMSwitch.schema.mof
DSCResources/xHyper-V/DSCResources/MSFT_xVhdFileDirectory/MSFT_xVhdFileDirectory.psm1
DSCResources/xHyper-V/README.md
DSCResources/xHyper-V/Tests/MSFT_xVMHyper-V/xVMHyper-V.Tests.ps1
DSCResources/xHyper-V/Tests/MSFT_xVMSwitch/xVMSwitch_BandwidthReservationMode.Tests.ps1
DSCResources/xHyper-V/appveyor.yml
DSCResources/xHyper-V/xHyper-V.psd1
DSCResources/xPendingReboot/DSCResources/MSFT_xPendingReboot/MSFT_xPendingReboot.psm1
DSCResources/xPendingReboot/DSCResources/MSFT_xPendingReboot/MSFT_xPendingReboot.schema.mof
DSCResources/xPendingReboot/README.md
DSCResources/xPendingReboot/Tests/xPendingReboot.tests.ps1
DSCResources/xPendingReboot/appveyor.yml
DSCResources/xPendingReboot/xPendingReboot.psd1
Lability.psd1
Lib/DiskImage.ps1
Lib/DscResource.ps1
Lib/DscResourceModule.ps1
Src/LabHostConfiguration.ps1
Src/LabResource.ps1
Tests/Src/LabResource.Tests.ps1

* Fixes verbose output in AddDiskImagePackage
* Removes erroneous bracket in GetDscResource
* Changes Get-LabHostConfiguration output to PSObjects for readability
* Updates bundled xHyper-V and xPendingReboot to latest versions
* Adds DestinationPath to custom resources to override the default resources location

Removes erroneous bracket in GetDscResource

---

Lib/BootStrap.ps1
Lib/DscResource.ps1
Resources.psd1

…tly in certain editors (like VS Code).

Trailing Space fix in Resources.psd1 and couple typo fixes

---

Config/Media.json
Readme.md
en-US/about_Bootstrap.help.txt
en-US/about_CustomResources.help.txt
en-US/about_Labililty.help.txt
en-US/about_Media.help.txt

* Adds Windows Management Framework v5 media IDs for Windows 8.1 and Server 2012 R2 evaluation editions
* Documentation updates

Adds WMF 5 media

---

.gitignore
.vscode/settings.json
Lability.psd1
Readme.md
Src/LabNode.ps1
Src/LabResource.ps1
Src/LabSwitch.ps1
Src/LabVM.ps1
Tests/Src/LabSwitch.Tests.ps1

* Fixes bug in Quick VM switch creation always creating the switch using the default switch name.
* Adds Get-LabNodeResourceList and Show-LabNodeResourceList cmdlets

Fixes bug in Quick VM switch creation

---

Lib/Internal.ps1
Lib/ZipArchive.ps1
Readme.md
Resources.psd1
Src/Lab.ps1
Src/LabConfiguration.ps1
Src/LabHostConfiguration.ps1
Src/LabResource.ps1
Tests/Src/Lab.Tests.ps1
Tests/Src/LabResource.Tests.ps1

Adds Write-Progress Output

---

Build.PSake.ps1
Lib/ConfigurationData.ps1
Lib/VirtualMachine.ps1
Lib/ZipArchive.ps1
Readme.md
Src/Lab.ps1
Src/LabVM.ps1
Src/LabVMDefault.ps1
Tests/Lib/ConfigurationData.Tests.ps1
Tests/Lib/VirtualMachine.Tests.ps1
Tests/Src/LabVM.Tests.ps1
Tests/Src/LabVMDefault.Tests.ps1

* Adds GuestIntegrationServices parameter - fixes #69
* Removes boot delay in Stop-Lab
* Adds file count/progress to ExpandZipArchiveItem
* Updates PSake Publish task dependency on Build task

Adds Guest Integration Services Support

---

Readme.md
Src/Lab.ps1
Tests/Src/Lab.Tests.ps1

Ensures that locked VMs do not prevent shutdown

Adds -Force switch to Stop-Lab

---

.vscode/tasks.json
Config/HostDefaults.json
Lib/ConfigurationData.ps1
Lib/UnattendXml.ps1
Readme.md
Src/LabHostDefault.ps1
Tests/Lib/ConfigurationData.Tests.ps1
Tests/Src/LabHostDefault.Tests.ps1

Set-LabHostDefault: Removes UpdatePath

---

Lib/VirtualMachine.ps1
Readme.md
Src/LabImage.ps1
Src/LabVM.ps1
Src/LabVMDisk.ps1
Tests/Lib/VirtualMachine.Tests.ps1
Tests/Src/LabImage.Tests.ps1
Tests/Src/LabVM.Tests.ps1
Tests/Src/LabVMDisk.Tests.ps1

Fixes custom media bug in Start-LabConfiguration

---

Config/Media.json
Readme.md
Src/LabHostConfiguration.ps1

* Fixes bug in Import-LabHostConfiguration with custom media

Adds Server 2016 TP 5 media

---

Lib/DscResource.ps1
Lib/VirtualMachine.ps1
Src/LabConfiguration.ps1
Src/LabSwitch.ps1
Src/LabVM.ps1
Src/LabVMDisk.ps1
Src/LabVMSnapshot.ps1
Tests/Lib/DiskImage.Tests.ps1

Let me know if it meets your standards :)

Add SupportsShouldProcess support to Remove-LabConfiguration

---

Lib/Internal.ps1
Readme.md
Resources.psd1
Src/LabVM.ps1
Tests/Lib/Internal.Tests.ps1

Throws when creating VM with an invalid name

---

Config/Media.json
Readme.md

Renames existing Win 10 media to LTSB

Adds Win 10 1607 media

---

Examples/CustomMedia.psd1
Readme.md
Src/LabImage.ps1
Tests/Src/LabImage.Tests.ps1

Adds descriptive error message for a missing WIM Image Name parameter

---

.vscode/settings.json
Config/Media.json
Examples/CustomMedia.psd1
Examples/NanoComputeExample.ps1
Examples/NanoComputeExample.psd1
Examples/NanoContainerExample.ps1
Examples/NanoContainerExample.psd1
Examples/NanoExample.psd1
Lib/ConfigurationData.ps1
Lib/DiskImage.ps1
Lib/Internal.ps1
Lib/WindowsImage.ps1
Lib/ZipArchive.ps1
Readme.md
Resources.psd1
Src/LabHostDefault.ps1
Src/LabImage.ps1
Src/LabMedia.ps1
Src/LabVMDefault.ps1
en-US/about_Media.help.txt

* Fixes #148
* Adds Server 2016 RTM Nano Server support and examples

Fixes bug where media 'Hotfixes' where not injected

---

Src/LabHostConfiguration.ps1

Ignores DismPath in Start- and Test-LabHostConfiguration

---

DSCResources/xHyper-V/DSCResources/MSFT_xVMHyperV/MSFT_xVMHyperV.psm1
Examples/TestLabGuide.psd1
Lib/DiskImage.ps1
Readme.md
Src/LabVMDisk.ps1
Src/LabVMDiskFile.ps1
Src/Private/Start-ShellHWDetectionService.ps1
Src/Private/Stop-ShellHWDetectionService.ps1
Tests/Lib/DiskImage.Tests.ps1
Tests/Src/LabVMDiskFile.Tests.ps1

Fixes calls to stop/start Shell Hardware Detection service on Server Core

---

Readme.md

Hi Ian - just a fix for a broken link in readme.md to @absolutejam 's article on lability.
Cheers

Fixed broken URL in ReadMe

---

Config/Media.json

Fixes #183. Verified that the Checksum is correct as well.

Fixing #183

---

Config/Media.json
Examples/NanoComputeExample.ps1
Examples/NanoComputeExample.psd1
Examples/NanoContainerExample.ps1
Examples/NanoContainerExample.psd1
Examples/NanoExample.ps1
Examples/NanoExample.psd1
Examples/TestLabGuide.ps1
Examples/TestLabGuide.psd1
Readme.md

* Adds Windows Management Framework 5.1 evaluation media
* Updates examples with xNetworking v3.0.0.0 breaking change
* Fixes #172

Updates Examples

---

Config/Media.json
Lib/Resource.ps1
Readme.md
Resources.psd1
Tests/Lib/BootStrap.Tests.ps1
Tests/Lib/Resource.Tests.ps1

* Fixes #205 
* Updates built-in Win 10 media to Creators Update (1703)

Throws error when downloaded resource checksum is incorrect

---

Lib/Resource.ps1
Src/Public/Get-LabStatus.ps1

* Catches authentication exceptions
* Fixes resource checksum error

Traps authentication exceptions in Get-LabStatus

---

Lability.psd1
Readme.md

* Throws error when downloaded resource checksum is incorrect (#205)
* Updates built-in Windows 10 evaluation and LTSB media with the 1703 'Creators Update' ISOs
* Adds Continuous Integration (CI) cmdlets
* Get-LabStatus - Retrieves DSC configuration deployment status
* Test-LabStatus - Tests DSC configuration deployment status has completed
* Wait-Lab - waits for DSC configurtion deployment to complete
* Adds DSC compilation cmdlets
* Start-DscCompilation - Compiles DSC configurations in parallel
* Adds Lability module cache cmdlets
* Install-LabModule - Install cached modules onto the Lability host
* Clear-ModulePath - Clear user's module path
* Clear-LabModuleCache - Empties Lability module cache

Releasing v0.11.0

---

Readme.md
Src/Public/Install-LabModule.ps1

Fixes bug in Install-LabModule deploying modules to the AllUsers scope

---

Config/HostDefaults.json
Readme.md
Src/Private/Expand-LabImage.ps1
Src/Private/Get-ConfigurationData.ps1
Src/Private/Resolve-LabSwitch.ps1
Src/Public/Set-LabHostDefault.ps1
Tests/Unit/Src/Private/Expand-LabImage.Tests.ps1
Tests/Unit/Src/Private/Get-ConfigurationData.Tests.ps1
Tests/Unit/Src/Private/Resolve-LabSwitch.Tests.ps1
Tests/Unit/Src/Public/Set-LabHostDefault.Tests.ps1

* Fixes bug resolving mounted disk image drive letter
* Fixes #233 
* Adds -DisableSwitchEnvironmentName parameter to Set-LabHostDefault
* Fixes #236 
* Updates README.md with BREAKING CHANGE for v0.12.0

Adds -DisableSwitchEnvironmentName Parameter

---

Lability.psd1
Readme.md
Src/Public/Set-LabHostDefault.ps1

* Fixes bug disabling DisableSwitchEnvironmentName

Releasing v0.12.2

---

Config/Media.json
Lability.psd1
Lability.psm1
Readme.md
Resources.psd1
Src/Private/Import-DismModule.ps1
Src/Private/New-LabVirtualMachine.ps1
Src/Private/Resolve-LabSwitch.ps1
Src/Public/New-LabImage.ps1
Tests/Unit/Src/Private/New-LabVirtualMachine.Tests.ps1
Tests/Unit/Src/Public/New-LabImage.Tests.ps1

* Adds DISM version check to Windows 10 and Server 2016 media images
* Fixes bug disabling DisableSwitchEnvironmentName in VM creation

Releasing v0.12.3

---

Readme.md
Src/Public/New-LabImage.ps1
Tests/Unit/Src/Public/New-LabImage.Tests.ps1

Fixes bug in DISM version check in Windows 10 images

---

Lability.psd1
Readme.md

* Adds Lability environment variables for all paths defined in the Lability host defaults
* Fixes bug in DISM version check in Windows 10 images

Releasing v0.12.4

---

en-US/about_Lability.help.txt

Fixed a small typo

---

en-US/about_CustomResources.help.txt

Fixed 'many' to may which contextually seems to be what was meant.

Fixed typo

---

Config/Media.json
Readme.md

* Fixes markdown violations/errors

Updates Windows 10 Evaluation Media to 1709

---

Config/Media.json
Readme.md
Src/Private/Convert-PSObjectToHashtable.ps1
Src/Public/Import-LabHostConfiguration.ps1
Tests/Unit/Src/Private/Convert-PSObjectToHashtable.Tests.ps1

 Fixes Custom Media Import Bug

---

Src/Private/New-Directory.ps1
Tests/Unit/Src/Private/New-Directory.Tests.ps1

Not that I found any errors in Lability itself, but noticed the parameters took array input, and that the function could not handle that on the Path parameter.

Minor bug in New-Directory and pester test for it

---

Readme.md
Src/Private/New-LabMedia.ps1

Adds WIM support to inline media definitions

---

Readme.md
Resources.psd1
Src/Public/Start-LabHostConfiguration.ps1
Tests/Unit/Src/Public/Start-LabHostConfiguration.Tests.ps1

Fixes IgnorePendingReboot bug in Start-LabHostConfiguration

---

Readme.md
Src/Private/Resolve-LabSwitch.ps1

Fixes virtual switch enumeration when NIC has a description

---

Lability.psd1
Readme.md
Src/Private/Import-LabDscResource.ps1

* Adds WIM support to inline media definitions (#273)
* Adds automatic checkpoints support (#266)
* Adds node (computer) name length validation (#109)
* Fixes `-IgnorePendingReboot` bug in `Start-LabHostConfiguration` (#278)
* Fixes bug in virtual switch enumeration when network interface has as description (#280)

Releasing 0.14.0

---

Examples/CustomDiskSize.psd1
Examples/CustomMedia.psd1
Examples/MultipleDiskExample.psd1
Readme.md
Resources.psd1
Src/Private/Assert-VirtualMachineHardDiskDriveParameter.ps1
Src/Private/New-DiskImage.ps1
Src/Private/Remove-LabVirtualMachineHardDiskDrive.ps1
Src/Private/Set-LabVirtualMachineHardDiskDrive.ps1
Src/Public/New-LabImage.ps1
Tests/Unit/Src/Private/Assert-VirtualMachineHardDiskDriveParameter.Tests.ps1
Tests/Unit/Src/Private/New-DiskImage.Tests.ps1
Tests/Unit/Src/Private/Remove-LabVirtualMachineHardDiskDrive.Tests.ps1
Tests/Unit/Src/Private/Set-LabVirtualMachineHardDiskDrive.Tests.ps1
Tests/Unit/Src/Public/New-LabImage.Tests.ps1
en-US/about_Media.help.txt

* Removes experimental support for attaching multiple VHD files to VMs (#218)
* Adds support for creating fixed and dynamic VHD files (#99)

Adds support for creating fixed/dynamic VHD files

---

Readme.md
Src/Private/Get-ConfigurationData.ps1
Src/Private/New-LabBootStrap.ps1
Src/Private/New-LabVirtualMachine.ps1
Src/Private/Set-LabBootStrap.ps1
Src/Private/Set-LabVMDiskFile.ps1
Src/Private/Set-LabVMDiskFileBootstrap.ps1
Src/Public/Set-LabVMDefault.ps1
Tests/Unit/Src/Private/Get-ConfigurationData.Tests.ps1
Tests/Unit/Src/Private/New-LabBootStrap.Tests.ps1
Tests/Unit/Src/Public/Set-LabVMDefault.Tests.ps1

Adds support for configuring the WSMan MaxEnvelopeSizeKb setting

---

Config/VMDefaults.json
Examples/NestedVirtualizationExample.psd1
Readme.md

Adds NestedVirtualizationExample.psd1 example

Changes default VM switch from 'Internal vSwitch' to 'Default Switch'

---

ChangeLog.md
Src/Private/Set-LabVMDiskFileModule.ps1
Tests/Unit/Src/Private/Set-LabVMDiskFileModule.Tests.ps1

Fixes bug with no external DSC resource dependencies defined in .mof

---

ChangeLog.md
Src/Private/Expand-LabImage.ps1
Src/Private/Expand-LabIso.ps1
Src/Private/Get-DiskImageDriveLetter.ps1
Src/Private/Get-LabVMSnapshot.ps1
Src/Private/New-DiskImage.ps1
Src/Private/New-DiskImageGpt.ps1
Src/Private/New-DiskImageMbr.ps1
Src/Private/New-EmptyDiskImage.ps1
Src/Private/New-LabVMSnapshot.ps1
Src/Private/New-LabVirtualMachine.ps1
Src/Private/Remove-LabVMSnapshot.ps1
Src/Private/Remove-LabVirtualMachine.ps1
Src/Private/Resolve-LabSwitch.ps1
Src/Private/Resolve-LabVMImage.ps1
Src/Private/Resolve-VhdHierarchy.ps1
Src/Private/Set-LabVMDiskFile.ps1
Src/Public/Checkpoint-Lab.ps1
Src/Public/Get-LabImage.ps1
Src/Public/New-LabImage.ps1
Src/Public/Restore-Lab.ps1
Src/Public/Start-Lab.ps1
Src/Public/Stop-Lab.ps1
Tests/Unit/Src/Private/Expand-LabImage.Tests.ps1
Tests/Unit/Src/Public/Register-LabMedia.Tests.ps1

 Use module-qualified names for Hyper-V and Storage commands

---

ChangeLog.md
Resources.psd1
Src/Private/Resolve-LabSwitch.ps1
Tests/Unit/Src/Private/Resolve-LabSwitch.Tests.ps1

Throws non-ambiguous error when multiple existing switches are detected

---

Src/Public/New-LabVM.ps1

Make MediaId param optional, and use configured media value as default

---

ChangeLog.md
Src/Private/Get-LabModuleCache.ps1
Src/Private/Invoke-LabModuleDownloadFromGitHub.ps1
Tests/Linting/Style.Tests.ps1
Tests/Unit/Src/Private/Get-LabModuleCache.Tests.ps1

Fixes bug in Github hosted modules where branch name contains '/'

---

ChangeLog.md
Config/LegacyMedia/WIN10_x64_Enterprise_1709_EN_Eval.json
Config/LegacyMedia/WIN10_x64_Enterprise_1803_EN_Eval.json
Config/LegacyMedia/WIN10_x64_Enterprise_1809_EN_Eval.json
Config/LegacyMedia/WIN10_x64_Enterprise_LTSB_2016_EN_Eval.json
Config/LegacyMedia/WIN10_x86_Enterprise_1709_EN_Eval.json
Config/LegacyMedia/WIN10_x86_Enterprise_1803_EN_Eval.json
Config/LegacyMedia/WIN10_x86_Enterprise_1809_EN_Eval.json
Config/LegacyMedia/WIN10_x86_Enterprise_LTSB_2016_EN_Eval.json
Config/Media.json
Lability.psm1
Src/Private/Resolve-ConfigurationDataPath.ps1
Src/Public/Get-LabMedia.ps1
Src/Public/Register-LabMedia.ps1

* Includes previous Windows 10 evaluation media definitions
* Adds -Legacy switch to Get-LabMedia and Register-LabMedia

Updates Windows 10 evaluation media to Windows 10 1903 (19H1)

---

ChangeLog.md
Lability.psd1
Lability.psm1
Src/Public/Export-LabImage.ps1
Src/Public/Get-LabHostDefault.ps1
Src/Public/Register-LabMedia.ps1
en-US/Lability.Resources.psd1
en-US/about_Media.help.txt

* Adds Export-LabImage cmdlet to export VHD(X) master/parent images
* Permits overriding media Id with -CustomId parameter when importing legacy media definitions or media from an external file/Uri

Adds Export-LabImage

---

ChangeLog.md
Examples/ModuleExample.psd1
Src/Private/Invoke-LabModuleCacheDownload.ps1
Tests/Unit/Src/Private/Invoke-LabModuleCacheDownload.Tests.ps1

Adds 'Latest' property to module info

---

ChangeLog.md
Config/HostDefaults.json
Src/Private/Copy-LabModule.ps1
Src/Private/Get-ConfigurationData.ps1
Src/Private/Get-LabVirtualMachineProperty.ps1
Src/Private/Remove-LabVMDisk.ps1
Src/Private/Remove-LabVirtualMachineHardDiskDrive.ps1
Src/Private/Resolve-ConfigurationPath.ps1
Src/Private/Resolve-LabVMDiskGenerationDiskPath.ps1
Src/Private/Resolve-LabVMDiskPath.ps1
Src/Private/Set-LabVMDisk.ps1
Src/Private/Set-LabVMDiskFile.ps1
Src/Private/Test-LabVMDisk.ps1
Src/Public/Get-LabVM.ps1
Src/Public/Remove-LabConfiguration.ps1
Src/Public/Set-LabHostDefault.ps1
Tests/Unit/Src/Private/Get-ConfigurationData.Tests.ps1
Tests/Unit/Src/Private/Resolve-LabVMDiskPath.Tests.ps1

Creates VM VHDs in an environment name subfolder (#78)

Adds environment name support for differencing VHDs

---

Readme.md

Updates broken 'The Ultimate Hyper-V Lab Tool' link

---

ChangeLog.md
Src/Private/Invoke-LabModuleCacheDownload.ps1
Src/Private/Invoke-LabModuleDownloadFromGitHub.ps1
Src/Private/Invoke-LabModuleDownloadFromPSGallery.ps1
Src/Private/Rename-LabModuleCacheVersion.ps1
Tests/Unit/Src/Private/Invoke-LabModuleDownloadFromGitHub.Tests.ps1
Tests/Unit/Src/Private/Invoke-LabModuleDownloadFromPSGallery.Tests.ps1
en-US/Lability.Resources.psd1

Adds version checking of downloaded modules

---

ChangeLog.md
Lability.psd1
Src/Private/Copy-Directory.ps1
en-US/Lability.Resources.psd1

* Retries failed resource file copy operations (fails after 5 attempts)

Releasing v0.19.1

---

ChangeLog.md
Config/LegacyMedia/WIN10_x64_Enterprise_1909_EN_Eval.json
Config/LegacyMedia/WIN10_x86_Enterprise_1909_EN_Eval.json
Config/Media.json
Src/Private/Get-LabMediaId.ps1
Src/Private/Resolve-LabMedia.ps1
Src/Private/Write-Verbose.ps1
Src/Private/Write-Warning.ps1
Src/Public/Get-LabMedia.ps1
Src/Public/New-LabImage.ps1
Src/Public/New-LabVM.ps1
Src/Public/Register-LabMedia.ps1
Src/Public/Reset-LabMedia.ps1
Src/Public/Test-LabMedia.ps1
Src/Public/Unregister-LabMedia.ps1
Tests/Linting/PSScriptAnalyzer.Tests.ps1
appveyor.yml
en-US/Lability.Resources.psd1

Adds aliases for latest Windows 10 evaluation media

Updates default Windows 10 evaluation media to Windows 10 20H1 (2004)

---

ChangeLog.md
Config/LegacyMedia/WIN10_x64_Enterprise_20H2_EN_Eval.json
Config/LegacyMedia/WIN10_x86_Enterprise_20H2_EN_Eval.json
Config/Media.json
Src/Private/New-LabBootStrap.ps1

* Disables network location wizard notification(s)
* Adds Windows 10 21H2 (2104) evaluation media
* Updates default Windows 10 evaluation media to Windows 10 21H1 (2104)

Adds Windows 10 21H2 (2104) evaluation media

---

Config/Media.json

Updates download url and checksum for WIN11_x64_Enterprise_22H2_EN_Eval

---

ChangeLog.md
Config/LegacyMedia/WIN11_x64_Enterprise_22H2_EN_Eval.json
Config/Media.json
Lability.psd1

* Updates default Windows 11 evaluation media to Windows 11 23H2 (2310)

Adds Windows 11 Enterprise 23H2 (2310) evaluation media
